version: "3.8"

services:
  backend:
    build:
      dockerfile: Dockerfile_django
      args:
        REPO_DIR: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker_dev
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8000"
    ports:
      - 8000:8000
    working_dir: /root/url-shortener
    env_file: .env_docker_dev
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "jf;lsdkaj"
      POSTGRES_DB: shortener




