FROM python:slim

WORKDIR /root/url-shortener

COPY ${REPO_DIR} /root/url-shortener/

RUN apt-get update && \
    apt-get -y install git build-essential libssl-dev libffi-dev libpq-dev && \
    pip3 install -r requirements.txt
