# Generated by Django 4.1.2 on 2022-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened', models.CharField(max_length=200)),
                ('redirect_to', models.CharField(max_length=200)),
            ],
        ),
    ]
