# Generated by Django 4.1.2 on 2022-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='shortened',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
